### ISSUE TITLE
Error trying to build FCM on Ionic 5 (iOS)

### ISSUE THREAD

**Issue by manel00** [chemerisuk/cordova-plugin-firebase-messaging#177]
Hello,

I moved a Ionic v5 project made for Android to iOS and want to do for the first time an iOS build. It is my first time building it, so i'm a little bit lost, can not understand what else should I install to make it finish.

Could you give me some advices to where should I start as well?

Thank you

Trace:

`
npm install @ionic-native/firebase-messaging
> cordova plugin add cordova-plugin-firebase-messaging
Installing "cordova-plugin-firebase-messaging" for android
Plugin dependency "cordova-plugin-firebase-analytics@5.0.0" already fetched, using that version.
Installing "cordova-plugin-firebase-analytics" for android
Plugin dependency "cordova-support-android-plugin@1.0.2" already fetched, using that version.
Dependent plugin "cordova-support-android-plugin" already installed on android.
Installing "cordova-support-google-services" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 9.0.0, failed version requirement: <9.0.0
Skipping 'cordova-support-google-services' for android
Subproject Path: CordovaLib
Subproject Path: app
Plugin dependency "cordova-support-android-plugin@1.0.2" already fetched, using that version.
Dependent plugin "cordova-support-android-plugin" already installed on android.
Plugin dependency "cordova-support-google-services@1.4.1" already fetched, using that version.
Installing "cordova-support-google-services" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 9.0.0, failed version requirement: <9.0.0
Skipping 'cordova-support-google-services' for android
Plugin dependency "cordova-plugin-androidx@3.0.0" already fetched, using that version.
Installing "cordova-plugin-androidx" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 9.0.0, failed version requirement: <9.0.0
Skipping 'cordova-plugin-androidx' for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-firebase-messaging" for ios
Plugin dependency "cordova-plugin-firebase-analytics@5.0.0" already fetched, using that version.
Installing "cordova-plugin-firebase-analytics" for ios
Running command: pod install --verbose

[!] Found multiple specifications for `FirebaseAnalytics (7.0.0)`:
- /Users/manel/.cocoapods/repos/cocoapods/Specs/e/2/1/FirebaseAnalytics/7.0.0/FirebaseAnalytics.podspec.json
- /Users/manel/.cocoapods/repos/trunk/Specs/e/2/1/FirebaseAnalytics/7.0.0/FirebaseAnalytics.podspec.json

Failed to install 'cordova-plugin-firebase-analytics': Error: pod: Command failed with exit code 1 Error output:
[!] Found multiple specifications for `FirebaseAnalytics (7.0.0)`:
- /Users/manel/.cocoapods/repos/cocoapods/Specs/e/2/1/FirebaseAnalytics/7.0.0/FirebaseAnalytics.podspec.json
- /Users/manel/.cocoapods/repos/trunk/Specs/e/2/1/FirebaseAnalytics/7.0.0/FirebaseAnalytics.podspec.json
    at ChildProcess.whenDone (/Users/manel/Documents/ionic_projects/topstock/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (node:events:378:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
Failed to install 'cordova-plugin-firebase-messaging': Error: pod: Command failed with exit code 1 Error output:
[!] Found multiple specifications for `FirebaseAnalytics (7.0.0)`:
- /Users/manel/.cocoapods/repos/cocoapods/Specs/e/2/1/FirebaseAnalytics/7.0.0/FirebaseAnalytics.podspec.json
- /Users/manel/.cocoapods/repos/trunk/Specs/e/2/1/FirebaseAnalytics/7.0.0/FirebaseAnalytics.podspec.json
    at ChildProcess.whenDone (/Users/manel/Documents/ionic_projects/topstock/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (node:events:378:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
pod: Command failed with exit code 1 Error output:
[!] Found multiple specifications for `FirebaseAnalytics (7.0.0)`:
- /Users/manel/.cocoapods/repos/cocoapods/Specs/e/2/1/FirebaseAnalytics/7.0.0/FirebaseAnalytics.podspec.json
- /Users/manel/.cocoapods/repos/trunk/Specs/e/2/1/FirebaseAnalytics/7.0.0/FirebaseAnalytics.podspec.json
[ERROR] An error occurred while running subprocess cordova.
        
        cordova plugin add cordova-plugin-firebase-messaging exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
`

**Comment by manel00** [comment]
I have more info, I went to the platforms/ios folder with XCode and I did Build, Build Failed and Don't know how to fix this error here, thank you =)

<img width="259" alt="image" src="https://user-images.githubusercontent.com/8410687/106969268-d09b1f80-674a-11eb-803a-b20e3fe3923c.png">

`- (void)messaging:(nonnull FIRMessaging *)messaging didReceiveRegistrationToken:(nonnull NSString *)deviceToken {
    NSLog(@"Device FCM Token: %@", deviceToken);
    if(deviceToken == nil) {
        fcmToken = nil;
        [FCMPlugin.fcmPlugin notifyFCMTokenRefresh:nil];
        return;
    }
    // Notify about received token.
    NSDictionary *dataDict = [NSDictionary dictionaryWithObject:deviceToken forKey:@"token"];
    [[NSNotificationCenter defaultCenter] postNotificationName:@"FCMToken" object:nil userInfo:dataDict];
    fcmToken = deviceToken;
    [FCMPlugin.fcmPlugin notifyFCMTokenRefresh:deviceToken];
    [self connectToFcm];
}
`

**Comment by manel00** [comment]
Why you closed it?
