### ISSUE TITLE
Not working on android nougat and below

### ISSUE THREAD

**Issue by noriellecruz** [chemerisuk/cordova-plugin-firebase-messaging#209]
Hi, we have tested it successfully on android 8 and above. It's working flawlessly but in android nougat, nothing is received, we've tried monitoring the console and we can confirm this. We've also tested this in AVD and the problem is the same, no notifications arrive from fcm.

App is in background, using AVD 7.1 for testing.

**Comment by noriellecruz** [comment]
This is the adb log while trying to send notification:

`
05-06 18:45:47.800 19152 19209 E eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
05-06 18:45:47.876  1393  1414 W audio_hw_generic: Not supplying enough data to HAL, expected position 20181214 , only wrote 20028960
05-06 18:45:48.955  1842  1842 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.auth.account.workaccount.START dat=chimera-action:com.google.android.gms.auth.account.workaccount.START cmp=com.google.android.gms/.chimera.PersistentApiService }
05-06 18:45:55.098  2350  2350 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
05-06 18:46:00.175  1842  1842 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.scheduler.ACTION_PROXY_SCHEDULE dat=chimera-action:com.google.android.gms.scheduler.ACTION_PROXY_SCHEDULE cmp=com.google.android.gms/.chimera.PersistentApiService }
05-06 18:46:02.350  2269  2615 I WorkerManager: dispose()
05-06 18:46:02.350  2269  2615 W A       : Queue length for executor EventBus is now 11. Perhaps some tasks are too long, or the pool is too small.
05-06 18:46:03.997  1842 17813 I NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.ads.social.GcmSchedulerWakeupService started execution. cause:4 exec_start_elapsed_seconds: 80936 [CONTEXT service_id=218 ]
05-06 18:46:04.034  2350 16881 E Ads     : Failed to connect to https://googleads.g.doubleclick.net/pagead/drt/m. No DSID retrieved.
05-06 18:46:04.036  1842 17812 I NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.ads.social.GcmSchedulerWakeupService finished executing. cause:4 result: 2 elapsed_millis: 49 uptime_millis: 49 exec_start_elapsed_seconds: 80936 [CONTEXT service_id=218 ]
05-06 18:46:10.790  2350  2350 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.potokens.service.START pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.GmsApiService }
05-06 18:46:10.790  2350  2350 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.potokens.service.START pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.GmsApiService }
05-06 18:46:25.891  2350  2350 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.potokens.service.START pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.GmsApiService }
05-06 18:46:26.706  2350  2927 I PhenotypeProcessReaper: Memory state is: 100
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter: Error sending ping
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter: java.net.ConnectException: Connection refused
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at java.net.PlainSocketImpl.socketConnect(Native Method)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:194)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at java.net.Socket.connect(Socket.java:605)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at com.android.okhttp.Connection.connectSocket(Connection.java:196)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at com.android.okhttp.Connection.connect(Connection.java:172)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at dsg.run(PG:14)
05-06 18:46:30.497 17924 18029 E GoogleConversionReporter:      at java.lang.Thread.run(Thread.java:761)
05-06 18:46:37.420  1842  1842 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.contextmanager.service.ContextManagerService.START pkg=com.google.android.gms }
05-06 18:46:40.348 19152 19156 I art     : Do partial code cache collection, code=26KB, data=31KB
05-06 18:46:40.348 19152 19156 I art     : After code cache collection, code=26KB, data=31KB
05-06 18:46:40.349 19152 19156 I art     : Increasing code cache capacity to 128KB
`

**Comment by noriellecruz** [comment]
this seems to be related with issue #135, was able to fix it by downgrading to 6.1.0. closing this now.
