### ISSUE TITLE
Error: pod: Command failed with exit code 31

### ISSUE THREAD

**Issue by buu700** [chemerisuk/cordova-plugin-firebase-messaging#28]
`cordova platform add ios` fails with the error below. Is that something you've seen before and know of a workaround for?

I'm running OS X El Capitan with ruby 2.5.1p57, gem 2.7.6, and cocoapods 1.5.3.

Thanks!

---

```
Installing "cordova-plugin-firebase-messaging" for ios
Failed to install 'cordova-plugin-firebase-messaging': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/buu700/cyph/cyph-phonegap-build/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:50695) UnhandledPromiseRejectionWarning: Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/buu700/cyph/cyph-phonegap-build/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:50695) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:50695) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by buu700** [comment]
Not sure what the problem was or what exactly fixed it, but I'm not seeing this error anymore after a `brew update ; brew upgrade; pod repo update`.

**Comment by burtontanner** [comment]
> Not sure what the problem was or what exactly fixed it, but I'm not seeing this error anymore after a `brew update ; brew upgrade; pod repo update`.

Thanks for your answer @buu700. The only thing I had to add was to update cocoapods.
`brew update; brew upgrade; sudo gem install cocoapods; pod repo update;`

**Comment by jkasten2** [comment]
`pod repo update` alone fixed the `Error: pod: Command failed with exit code 31` error I seen with another package. Updating cocoapods it self via `brew update; brew upgrade; sudo gem install cocoapods;` is probably not necessary.
