### ISSUE TITLE
Android Fatal Crash: Default FirebaseApp is not initialized 

### ISSUE THREAD

**Issue by KindTech** [chemerisuk/cordova-plugin-firebase-messaging#6]
I added this plugin to my Ionic 2 app and it crashes as soon as I deploy it to an android device in debug mode.

The relevant error in the stack trace:

E/AndroidRuntime( 4692): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp.app/com.myapp.app.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.myapp.app. Make sure to call FirebaseApp.initializeApp(Context) first.

E/AndroidRuntime( 4692): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2695)

E/AndroidRuntime( 4692): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)

E/AndroidRuntime( 4692): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)

E/AndroidRuntime( 4692): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)

E/AndroidRuntime( 4692): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime( 4692): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime( 4692): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime( 4692): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime( 4692): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime( 4692): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime( 4692): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

E/AndroidRuntime( 4692): Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.myapp.app. Make sure to call FirebaseApp.initializeApp(Context) first.

E/AndroidRuntime( 4692): 	at com.google.firebase.FirebaseApp.getInstance(Unknown Source)

E/AndroidRuntime( 4692): 	at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)

E/AndroidRuntime( 4692): 	at com.google.firebase.messaging.FirebaseMessaging.getInstance(Unknown Source)

E/AndroidRuntime( 4692): 	at by.chemerisuk.cordova.firebase.FirebaseMessagingPlugin.pluginInitialize(FirebaseMessagingPlugin.java:40)

E/AndroidRuntime( 4692): 	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58)

E/AndroidRuntime( 4692): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)

E/AndroidRuntime( 4692): 	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)

E/AndroidRuntime( 4692): 	at org.apache.cordova.PluginManager.init(PluginManager.java:86)

E/AndroidRuntime( 4692): 	at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:115)

E/AndroidRuntime( 4692): 	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)

E/AndroidRuntime( 4692): 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)

E/AndroidRuntime( 4692): 	at com.myapp.app.MainActivity.onCreate(MainActivity.java:39)

E/AndroidRuntime( 4692): 	at android.app.Activity.performCreate(Activity.java:6178)

E/AndroidRuntime( 4692): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)

E/AndroidRuntime( 4692): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648)

**Comment by KindTech** [comment]
Additional Info: I have the following plugins installed:

        "cordova-plugin-appavailability": "^0.4.2",
        "cordova-plugin-applepay": "^2.1.4",
        "cordova-plugin-camera": "^2.4.1",
        "cordova-plugin-cocoapod-support": "^1.3.0",
        "cordova-plugin-compat": "^1.1.0",
        "cordova-plugin-console": "1.0.5",
        "cordova-plugin-device": "1.1.4",
        "cordova-plugin-firebase-analytics": "^0.9.5",
        "cordova-plugin-firebase-dynamiclinks": "^0.9.6",
        "cordova-plugin-firebase-hooks": "^0.9.6",
        "cordova-plugin-firebase-messaging": "^0.9.0",
        "cordova-plugin-geolocation": "^2.4.3",
        "cordova-plugin-inappbrowser": "^1.7.1",
        "cordova-plugin-keyboard": "^1.1.5",
        "cordova-plugin-mauron85-background-geolocation": "^2.2.5",
        "cordova-plugin-request-location-accuracy": "^2.2.1",
        "cordova-plugin-splashscreen": "~4.0.1",
        "cordova-plugin-statusbar": "2.2.2",
        "cordova-plugin-stripe": "^1.4.1",
        "cordova-plugin-whitelist": "1.3.1",
        "cordova-plugin-x-socialsharing": "^5.1.8",
        "cordova-sqlite-storage": "^2.0.4",

**Comment by chemerisuk** [comment]
Try version 0.10.0

**Comment by KindTech** [comment]
That fixed it. Thanks!

**Comment by mehtapriyanka123** [comment]
The app is crashing-I am a beginner i don't know how to solve it
The relevant error in the stack trace:

2019-03-31 21:56:52.592 16821-16821/com.example.splashscreenn E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.splashscreenn, PID: 16821
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.splashscreenn/com.example.splashscreenn.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.splashscreenn. Make sure to call FirebaseApp.initializeApp(Context) first.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.splashscreenn. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@16.1.0:245)
        at com.google.firebase.auth.FirebaseAuth.getInstance(Unknown Source:1)
        at com.example.splashscreenn.MainActivity.onCreate(MainActivity.java:49)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 


Please tell me the solution!!!
