### ISSUE TITLE
ArgumentError - Illformed requirement `"$POD_FIREBASE_VERSION"`

### ISSUE THREAD

**Issue by fermedina** [chemerisuk/cordova-plugin-firebase-messaging#88]
To install the plugin, the pod install command fail.

If I open the Podfile of platforms/ios folder and change `pod 'Firebase/Messaging', '$POD_FIREBASE_VERSION'` by `pod 'Firebase/Messaging', '~> 6.1.0'` the pod install don't fail.

```bash
### Error

ArgumentError - Illformed requirement `"$POD_FIREBASE_VERSION"`
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.2/lib/cocoapods-core/requirement.rb:63:in `parse'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.2/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.2/lib/cocoapods-core/requirement.rb:88:in `map!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.2/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.2/lib/cocoapods-core/requirement.rb:34:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.2/lib/cocoapods-core/requirement.rb:34:in `create'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.2/lib/cocoapods-core/dependency.rb:115:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.2/lib/cocoapods-core/podfile/target_definition.rb:899:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.2/lib/cocoapods-core/podfile/target_definition.rb:899:in `block in pod_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.2/lib/cocoapods-core/podfile/target_definition.rb:895:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.2/lib/cocoapods-core/podfile/target_definition.rb:895:in `pod_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.2/lib/cocoapods-core/podfile/target_definition.rb:96:in `non_inherited_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.2/lib/cocoapods-core/podfile/target_definition.rb:74:in `dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:43:in `block in from_podfile'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:42:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:42:in `from_podfile'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:76:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:272:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:272:in `create_analyzer'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:167:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:136:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.2/lib/cocoapods/command/install.rb:48:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by chemerisuk** [comment]
@fermedina Bugfix published in v2.1.5
